//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalanceProject2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BalanceDb : DbContext
    {
        public BalanceDb()
            : base("name=BalanceDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Headings> Headings { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Personal_accounts> Personal_accounts { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Saldo> Saldo { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<SaldoView> SaldoView { get; set; }
    }
}
